run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - copyloopvar
    - gocritic
    - gocyclo
    - misspell
    - revive
    - gosec
    - unconvert
    - unparam
    - goconst
    - dupl
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - whitespace
    - prealloc
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Minor memory optimization, reduces readability

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      - unnamedResult
      - ifElseChain
      - octalLiteral
      - paramTypeCombine

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: exported
        disabled: true
      - name: unused-parameter
        disabled: true  # Context parameters often required for interface compatibility
      - name: var-naming
        disabled: true  # Allow Id vs ID (comes from JSON/Airtable conventions)

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G115  # Integer overflow conversion (too many false positives)

  whitespace:
    multi-if: true
    multi-func: true

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

  whitespace:
    multi-if: true
    multi-func: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude known issues in generated code
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"  # Empty branch

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
